### ISSUE TITLE
Issue building with angular-cli 1.0.0

### ISSUE THREAD

**Issue by rustygreen** [BenjaminBrandmeier/angular2-image-gallery#31] opened 2017-03-25 01:14 UTC
After upgrading to the latest Angular and CLI version, I can no longer build the project when "angular2-image-gallery" is include. I created a brand new project with the new angular-cli 1.0.0 and only added the "angular2-image-gallery" module (and dependencies) - per the README instructions (I have a working instance back under angular-cli version 1.0.0-RC1). I now get the following error ANY time I try to build (regardless of whether I am using AOT or not):

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/some-app/node_modules/angular2-image-gallery/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in C:/some-app/node_modules/angular2-image-gallery/node_modules/@angular/core/src/metadata.d.ts, resolving symbol
NgModule in C:/some-app/node_modules/angular2-image-gallery/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in C:/some-app/node_modules/angular2-image-gallery/node_modules/@angular/core/index.d.ts, resolv
ing symbol Angular2ImageGalleryModule in C:/some-app/node_modules/angular2-image-gallery/app/angular2imagegallery.module.ts, resolving symbol Angular2ImageGalleryModule in C:/some-app/node_modules/angular2-image-gallery/app/
angular2imagegallery.module.ts
```

**Environment:**
OS: Windows 10
Node: 6.9.1
Angular CLI: 1.0.0

Any thoughts? This seems related: https://github.com/angular/angular-cli/issues/3707

I'll post the code if needed. Thanks!

**Comment by born2net** [comment] 2017-03-25 22:00
I have the same issue, can't use ng-cli 1.0 due to this bug.
```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/msweb/studioweb/node_modules/ng-mslib/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol Injectable in C:/msweb/studioweb/node_modules/ng-mslib/node_modules/@angular/core/src/di.d.ts, resolving symbol Injectable in C:/msweb/studioweb/node_modules/ng-mslib/node_modules/@angular/core/src/core.d.ts, resolving symbol Injectable in C:/msweb/studioweb/node_modules/ng-mslib/node_modules/@angular/core/index.d.ts, resolving symbol NgmslibService in C:/msweb/studioweb/node_modules/ng-mslib/dist/services/ngmslib.service.d.ts, resolving symbol NgmslibService in C:/msweb/studioweb/node_modules/ng-mslib/dist/services/ngmslib.service.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './locale/app/app-module.ngfactory' in 'C:\msweb\studioweb\src'
 @ ./src/main.ts 6:0-71
 @ multi ./src/main.ts
```

worked fine in release rc.1

**Comment by born2net** [comment] 2017-03-25 22:12
@rustygreen still having the same issue?

**Comment by rustygreen** [comment] 2017-03-25 22:29
@born2net, yes I am. I have not found a fix yet.

**Comment by born2net** [comment] 2017-03-25 23:00
@rustygreen Rob helped out, I had to change in my package.json lib dependencies to peerDependencies and fixed the issue.

**Comment by aldo-roman** [comment] 2017-03-25 23:14
Hi @born2net can you specify how your package.json file ended?

Mine is
```
"dependencies": {
  },
  "devDependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.2.0",
    "zone.js": "^0.8.5",
    "@types/core-js": "^0.9.39",
    "typescript": "^2.2.1"
  },
  "peerDependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/platform-browser": "^4.0.0"
  }
```

but still reproduce the error

**Comment by born2net** [comment] 2017-03-25 23:19
see here:
https://github.com/born2net/ng-mslib/blob/master/package.json

**Comment by BenjaminBrandmeier** [comment] 2017-03-26 20:12
Thanks for your support guys. I moved the angular dependencies to peerDependencies for now and published a new version of angular2-image-gallery to NPM (0.6.2).
However, if you'd like to use the gallery with Angular-Cli 1.0.0 there are two things to consider:

1. Import BrowserAnimationsModule in your project:
```
  imports: [
    Angular2ImageGalleryModule,
    BrowserAnimationsModule, <---- add this to your project
    BrowserModule,
    FormsModule,
    HttpModule,
  ],
```

2. IE 11 currently not working
I only had a quick look at this and it didn't get pass the Loading... screen. I'm planning on having a clean migration to Angular 4 and take care about browser compatibility as soon as I find some free time somewhen. But I'm also happy to accept PRs as you know.

If there are any different issues with the new version regarding angular-cli 1.0.0 please raise a new issue for this. I will close this one for now.

**Comment by bfan1256** [comment] 2017-03-30 04:29
I'm still receiving the same error as @rustygreen even after your 0.6.2 update.

**Comment by BenjaminBrandmeier** [comment] 2017-04-05 20:44
It seems like we've to do some work for being AOT-compatible: 
https://github.com/rangle/angular-2-aot-sandbox

If anyone finds and/or removes the remaining issues in the code or knows of an easy way to find the 'not-aot-compatible' lines of code, please contribute. :)

Otherwise I will have a look at this as soon as I'll find some free time.

**Comment by bfan1256** [comment] 2017-04-05 20:46
I got the entire thing to work by downloading your source code and adding it to my folder structure and then importing each into the app module and declaring/providing the service.

**Comment by BenjaminBrandmeier** [comment] 2017-04-05 20:50
Interesting, so we have a dirty workaround. ;)

So it could also be related to my whacky approach to create the library...

However, this issue remains and we need to fix it.

**Comment by BenjaminBrandmeier** [comment] 2017-04-10 20:21
Ok folks. I change the library creation process to use the NGC compiler rather than the TSC. With the new approach even AOT shouldn't be an issue any more.

Could one of you retry with the newly published angular2-image-gallery 0.7.0 version?

**Comment by BenjaminBrandmeier** [comment] 2017-04-14 17:14
Update for `ng build --prod` included in 0.7.1.

Would love to hear feedback regarding this issue. Could somebody test it? Otherwise I'll close this issue.

**Comment by stepanic** [comment] 2017-04-20 22:51
I have issue with v0.7.4

```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/flex-layout: 2.0.0-beta.7
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
@angular/compiler-cli: 4.0.2

$ ng serve
** NG Live Development Server is running on http://localhost:4200 **
Hash: 3ae9f186dbc714358bca
Time: 15372ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 531 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 108 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.3 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.11 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the fu
nction or lambda with a reference to an exported function, resolving symbol NgModule in /Users/matijastepanic/git/inzrak/web/node_modules/angular2-image-gall
ery/node_modules/@angular/core/core.d.ts, resolving symbol Angular2ImageGalleryModule in /Users/matijastepanic/git/inzrak/web/node_modules/angular2-image-gal
lery/angular2imagegallery.module.d.ts, resolving symbol Angular2ImageGalleryModule in /Users/matijastepanic/git/inzrak/web/node_modules/angular2-image-galler
y/angular2imagegallery.module.d.ts
webpack: Failed to compile.

```

**Comment by stepanic** [comment] 2017-04-20 22:56
@BenjaminBrandmeier ignore my last comment because when I execute this:
```
rm -rf node_modules
npm install
```
And all errors are gone :D

This module is fantastic Photo Gallery, good job!

**Comment by BenjaminBrandmeier** [comment] 2017-04-21 03:49
@stepanic Thanks for the feedback. :)
I will close this issue.

**Closed by BenjaminBrandmeier** 2017-04-21 03:49 UTC
Labels: bug
